#!/usr/bin/env bash

__delete_old_instances() {
  local terminst_tmp=$(mktemp ${TMPDIR:-/var/tmp}/gcloud-cleanup-terminst.XXXXX)

  log 'fetching terminated instances'

  ${GCLOUD_READ_EXE} compute instances list --format json | \
    jq -r '.[] | select(.status == "TERMINATED") | .name' > ${terminst_tmp}

  if [[ -s ${terminst_tmp} ]] ; then
    set +o errexit
    cat ${terminst_tmp} | \
      xargs -- ${GCLOUD_WRITE_EXE} compute instances delete \
        --zone=${GCLOUD_ZONE} \
        --verbosity=${GCLOUD_VERBOSITY} \
        -q \
        --${GCLOUD_LOG_HTTP}
    set -o errexit
    log 'deleted instances' n=$(wc -l ${terminst_tmp} | awk '{ print $1 }')
  else
    log 'nothing to clean up, skipping'
  fi

  rm -f ${terminst_tmp}
}
