#!/usr/bin/env bash

__delete_old_instances_supports_multizone() {
  echo 1
}

__delete_old_instances_parallel() {
  local terminst_tmp=$(mktemp ${TMPDIR:-/var/tmp}/gcloud-cleanup-terminst.XXXXX)

  log 'fetching terminated instances' zone=${GCLOUD_ZONE}

  ${GCLOUD_READ_EXE} compute instances list --format json | \
    jq -r '.[] | select(.status == "TERMINATED") | .name' > ${terminst_tmp}

  if [[ -s ${terminst_tmp} ]] ; then
    set +o errexit
    export -f __delete_old_instances_chunk
    cat ${terminst_tmp} | \
      xargs -n 5 -I {} -- bash -c '__delete_old_instances_chunk "$@"' _ {}
    set -o errexit
    log 'deleted instances' n=$(wc -l ${terminst_tmp} | awk '{ print $1 }')
  else
    log 'nothing to clean up, skipping'
  fi

  rm -f ${terminst_tmp}
}

__delete_old_instances_chunk() {
  ${GCLOUD_WRITE_EXE} compute instances delete \
    --zone=${GCLOUD_ZONE} \
    --verbosity=${GCLOUD_VERBOSITY} \
    -q \
    --${GCLOUD_LOG_HTTP} "$@"
  sleep ${GCLOUD_CLEANUP_INSTANCES_LOOP_SLEEP}
}
