#!/usr/bin/env bash

__set_diff() {
  local cattmp="$(mktemp ${TMPDIR:-/var/tmp}/gcloud-cleanup.XXXXX)"

  cat "$1" | sed 's/^/a /' > "$cattmp"
  cat "$2" | sed 's/^/b /' >> "$cattmp"
  cat "$cattmp" | sort -k2 | uniq -f1 | grep '^b ' | sed 's/^b //'

  rm -f "${cattmp}"
}
