#!/usr/bin/env bash

log(){
  msg=$1
  shift
  if [[ ! $* =~ level= ]] ; then
    echo date=$(date -u +%Y-%m-%dT%H:%M:%S) level=info msg=\"$msg\" $*
  else
    echo date=$(date -u +%Y-%m-%dT%H:%M:%S) msg=\"$msg\" $*
  fi
}
