#!/usr/bin/env bash

log(){
  msg=$1
  shift
  local record="date=$(date -u +%Y-%m-%dT%H:%M:%S) msg=\"$msg\""
  if [[ ! $* =~ level= ]] ; then
    record="$record level=info"
  fi
  echo $record $*
}
