#!/usr/bin/env bash

HERE="$(dirname ${BASH_SOURCE[0]})"
PATH="$HERE/google-cloud-sdk/bin:$PATH"

: ${GCLOUD_READ_EXE:=${HERE}/google-cloud-sdk/bin/gcloud}
: ${GCLOUD_WRITE_EXE:=${HERE}/google-cloud-sdk/bin/gcloud}
: ${GCLOUD_CLEANUP_ZONES:=us-central1-f us-central1-b}
: ${GCLOUD_VERBOSITY:=info}
: ${GCLOUD_LOG_HTTP:=log-http}
: ${GCLOUD_CLEANUP_ENTITIES:=instances images}
: ${GCLOUD_CLEANUP_LOOP_SLEEP:=10}
: ${GCLOUD_CLEANUP_ONCE:=}
: ${GCLOUD_CLEANUP_IMAGE_LIMIT:=100}
: ${JOB_BOARD_URL:=http://localhost:4567}

cat <<EOF
Starting up gcloud-cleanup with settings:

  GCLOUD_CLEANUP_ENTITIES=${GCLOUD_CLEANUP_ENTITIES}
  GCLOUD_CLEANUP_IMAGE_LIMIT=${GCLOUD_CLEANUP_IMAGE_LIMIT}
  GCLOUD_CLEANUP_LOOP_SLEEP=${GCLOUD_CLEANUP_LOOP_SLEEP}
  GCLOUD_CLEANUP_ZONES=${GCLOUD_CLEANUP_ZONES}
  GCLOUD_LOG_HTTP=${GCLOUD_LOG_HTTP}
  GCLOUD_PROJECT=${GCLOUD_PROJECT}
  GCLOUD_VERBOSITY=${GCLOUD_VERBOSITY}

EOF

export GCLOUD_CLEANUP_IMAGE_LIMIT
export GCLOUD_CLEANUP_ZONES
export GCLOUD_LOG_HTTP
export GCLOUD_PROJECT
export GCLOUD_READ_EXE
export GCLOUD_VERBOSITY
export GCLOUD_WRITE_EXE
export JOB_BOARD_URL

if [[ ${GCLOUD_CLEANUP_DEBUG} || ${DEBUG} ]] ; then
  set -o xtrace
fi

set -o errexit

echo -en "Active account: "
${GCLOUD_READ_EXE} auth list --format json | \
  jq -r .active_account 2>/dev/null || echo unknown

for f in ${HERE}/functions/* ; do
  source "$f"
done

while true ; do
  for entity in ${GCLOUD_CLEANUP_ENTITIES} ; do
    for zone in ${GCLOUD_CLEANUP_ZONES} ; do
      export GCLOUD_ZONE="${zone}"
      __delete_old_${entity} &
    done
  done

  wait

  if [[ ${GCLOUD_CLEANUP_ONCE} ]] ; then
    exit 0
  fi

  log 'sleeping' seconds=${GCLOUD_CLEANUP_LOOP_SLEEP}
  sleep ${GCLOUD_CLEANUP_LOOP_SLEEP}
done
