#!/usr/bin/env bash

HERE="$(dirname ${BASH_SOURCE[0]})"
PATH="$HERE/google-cloud-sdk/bin:$PATH"

: ${GCLOUD_READ_EXE:=${HERE}/google-cloud-sdk/bin/gcloud}
: ${GCLOUD_WRITE_EXE:=${HERE}/google-cloud-sdk/bin/gcloud}
: ${GCLOUD_ZONE:=us-central1-f}
: ${GCLOUD_VERBOSITY:=info}
: ${GCLOUD_LOG_HTTP:=true}
: ${GCLOUD_CLEANUP_LOOP_SLEEP:=10}
: ${GCLOUD_CLEANUP_ONCE:=}
: ${GCLOUD_CLEANUP_IMAGE_LIMIT:=100}
: ${JOB_BOARD_URL:=http://localhost:4567}

cat <<EOF
Starting up gcloud-cleanup with settings:

  GCLOUD_PROJECT=${GCLOUD_PROJECT}
  GCLOUD_ZONE=${GCLOUD_ZONE}
  GCLOUD_VERBOSITY=${GCLOUD_VERBOSITY}
  GCLOUD_LOG_HTTP=${GCLOUD_LOG_HTTP}
  GCLOUD_CLEANUP_LOOP_SLEEP=${GCLOUD_CLEANUP_LOOP_SLEEP}
  GCLOUD_CLEANUP_IMAGE_LIMIT=${GCLOUD_CLEANUP_IMAGE_LIMIT}

EOF

export GCLOUD_CLEANUP_IMAGE_LIMIT
export GCLOUD_LOG_HTTP
export GCLOUD_PROJECT
export GCLOUD_READ_EXE
export GCLOUD_VERBOSITY
export GCLOUD_WRITE_EXE
export GCLOUD_ZONE
export JOB_BOARD_URL

echo -en "Active account: "
${GCLOUD_READ_EXE} auth list --format json | jq -r .active_account

source "${HERE}/functions/log"
source "${HERE}/functions/__delete_old_instances"
source "${HERE}/functions/__delete_old_images"

set -o errexit

while true ; do
  __delete_old_instances
  __delete_old_images

  if [[ ${GCLOUD_CLEANUP_ONCE} ]] ; then
    exit 0
  fi

  log 'sleeping' seconds=${GCLOUD_CLEANUP_LOOP_SLEEP}
  sleep ${GCLOUD_CLEANUP_LOOP_SLEEP}
done
