package gcloudcleanup

import "os"

func init() {
	for _, envVar := range []string{
		"GCLOUD_CLEANUP_ACCOUNT_JSON",
		"GCLOUD_CLEANUP_INSTANCE_FILTERS",
		"GCLOUD_CLEANUP_JOB_BOARD_URL",
		"GCLOUD_CLEANUP_PROJECT_ID",
		"GCLOUD_CLEANUP_RATE_LIMIT_DURATION",
		"GCLOUD_CLEANUP_RATE_LIMIT_MAX_CALLS",
		"GCLOUD_CLEANUP_RATE_LIMIT_PREFIX",
		"GCLOUD_CLEANUP_RATE_LIMIT_REDIS_URL",
		"GCLOUD_CLEANUP_ZONES",
	} {
		os.Unsetenv(envVar)
	}
}
